name: Docker image CI
on:
  push:
    branches: [ "master" ]

jobs:
    deploy:
      name: Docker build
      runs-on: ubuntu-latest
      steps: 
        - name: Check out th e repo
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build app image
          run: |
            docker build --platform linux --tag mateovalenzuela/frontinversiones:latest .
            
        - name: Publish app image
          run: |
            docker push mateovalenzuela/frontinversiones:latest
        
        - name: Login to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

        - name: Deploy to Azure Web App
          run: |
            az webapp config container set \
              --name mateovalenzuela-comparador-de-inversiones \
              --resource-group proyecto-inversiones \
              --docker-custom-image-name mateovalenzuela/frontinversiones:latest \
              --docker-registry-server-url https://index.docker.io/v1/ \
              --docker-registry-server-user ${{ secrets.DOCKER_USERNAME }} \
              --docker-registry-server-password ${{ secrets.DOCKER_TOKEN }}

        - name: Restart Azure Web App to apply new image
          run: |
            az webapp restart --name mateovalenzuela-comparador-de-inversiones --resource-group proyecto-inversiones
