name: Docker image CI
on:
  push:
    branches: [ "master" ]

jobs:
    deploy:
      name: Docker build
      runs-on: ubuntu-latest
      steps: 
        - name: Check out th e repo
          uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and Push docker image
          run: |
            docker build --platform linux --tag mateovalenzuela/frontinversiones:latest .
            docker push mateovalenzuela/frontinversiones:latest  

        - name: Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy with Docker Compose
          run: |
            az webapp config container set \
              --name mateovalenzuela-comparador-de-inversiones \
              --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
              --multicontainer-config-type compose \
              --multicontainer-config-file ./docker-compose.yml

            