name: Docker image CI
on:
  push:
    branches: [ "master" ]

jobs:
    deploy:
      name: Docker build
      runs-on: ubuntu-latest
      steps: 
        - name: Check out th e repo
          uses: actions/checkout@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

        - name: Build and Push docker image
          run: |
            IMAGE_TAG=${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            docker build --platform linux --tag $IMAGE_TAG .
            docker push $IMAGE_TAG

        - name: Update Docker Compose
          run: |
            sed -i "s|${{ secrets.DOCKER_IMAGE_NAME }}|${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}|g" docker-compose.yml

        - name: Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy with Docker Compose
          run: |
            az webapp config container set \
              --name ${{ secrets.AZURE_WEBAPP_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
              --multicontainer-config-type compose \
              --multicontainer-config-file ./docker-compose.yml

        - name: Restart Azure App Service
          run: |
            az webapp stop --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
            az webapp start --name ${{ secrets.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP_NAME }}
        
        - name: Validate Deployment
          run: |
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.URL_APP }})
            if [ $RESPONSE -ne 200 ]; then
              echo "Deployment failed with HTTP status $RESPONSE"
              exit 1
            fi
