name: CI/CD with Docker Compose for Azure App Service

on:
  push:
    branches: [ "master" ]  # Cambia según la rama que uses para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Paso 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Paso 3: Build and push backend image
      - name: Build and push backend image
        run: |
          docker build --platform linux --tag mateovalenzuela/apiinversiones:latest ./backend
          docker push mateovalenzuela/apiinversiones:latest

      # Paso 4: Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build --platform linux --tag mateovalenzuela/frontinversiones:latest ./frontend
          docker push mateovalenzuela/frontinversiones:latest

      # Paso 5: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Paso 6: Deploy using Docker Compose
      - name: Deploy with Docker Compose
        uses: azure/webapps-deploy@v2
        with:
          app-name: mateovalenzuela-comparador-de-inversiones
          slot-name: Production
          package: ./  # Directorio que contiene el docker-compose.yml
