name: Docker image CI
on:
  push:
    branches: [ "master" ]

jobs:
    deploy:
      name: Docker build
      runs-on: ubuntu-latest
      steps: 
        - name: Check out th e repo
          uses: actions/checkout@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Build app image
          run: |
            docker build --platform linux --tag mateovalenzuela/frontinversiones:latest .
            
        - name: Publish app image
          run: |
            docker push mateovalenzuela/frontinversiones:latest
        
        - name: App service auth
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'mateovalenzuela-comparador-de-inversiones'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'mateovalenzuela/frontinversiones:latest'

